all : paper.pdf

paper.pdf : paper.tex
	pdflatex $^

clean :
	rm -rf *.o *~ *.pdf *.log *.aux *.png paper.dvi paper.html paper.idv paper.css paper.4ct paper.5tc paper.lg paper.out paper.tmp paper.xref

